/**
 * 阶段数据表 —— 全项目唯一真源。
 * 顺序固定：晴天 → 多云 → 阴天 → 雨 → 暴雨 → 强对流。
 * 想调节难度或特效强度，只改这张表即可，不需要动任何逻辑。
 */

import type { StageDef } from './types'

export const CARRY_MAX = 0.25
export const COMBO_WINDOW_MS = 700
const COMBO_TIERS = [8, 16, 28] as const
const COMBO_MULTIPLIERS = [1, 1.25, 1.5, 1.75] as const

export const STAGES: readonly StageDef[] = [
  {
    index: 0,
    key: 'sunny',
    name: '晴天',
    tagline: '万里无云，一点雨的意思都没有',
    hint: '点我求雨',
    advanceGain: 0.22,
    decayPerSec: 0.05,
    graceMs: 250,
    palette: {
      skyTop: '#2f8fe0',
      skyMid: '#87c8f5',
      skyBottom: '#ffe6b0',
      sun: '#fff6c2',
      cloud: '#ffffff',
      cloudShade: '#dbe9f7',
      ground: '#7fbf6a',
      accent: '#ffb85c',
      text: '#0d2b45',
      vignette: '#1b4f7a',
      vignetteStrength: 0.05,
    },
    wind: { amp: 4, freq: 0.45, dodge: 0, dodgeRadius: 2.2, dodgeLag: 0.32, jitter: 0.05 },
    audio: {
      ambient: 'breeze',
      rainGain: 0,
      windGain: 0.04,
      droneGain: 0,
      hailPerSecond: 0,
      thunderPerMinute: 0,
      thunderAudible: false,
      siren: false,
      click: 'chime',
    },
    effects: {
      sun: 1,
      cloud: 0.12,
      cloudLayers: 3,
      dust: 0.3,
      leaves: 0,
      rain: 0,
      rainLength: 0.9,
      ripples: 0,
      waterDrops: 0,
      hail: 0,
      debris: 0,
      lightningPerSecond: 0,
      vortex: 0,
      streaks: 0.1,
      shake: 0,
      strobe: 0,
      contrast: 0,
      heat: 0.55,
    },
    prayers: ['风来', '云起', '借点云', '天听我言', '晴久必雨'],
  },
  {
    index: 1,
    key: 'cloudy',
    name: '多云',
    tagline: '云层初聚，风开始有了主意',
    hint: '云在聚了！',
    advanceGain: 0.2,
    decayPerSec: 0.07,
    graceMs: 250,
    palette: {
      skyTop: '#5d92c4',
      skyMid: '#9fbdd6',
      skyBottom: '#e2e8ec',
      sun: '#f7f1cd',
      cloud: '#ffffff',
      cloudShade: '#b9c9d8',
      ground: '#6fa768',
      accent: '#8ecae6',
      text: '#12303f',
      vignette: '#2a4459',
      vignetteStrength: 0.12,
    },
    wind: { amp: 12, freq: 0.5, dodge: 0, dodgeRadius: 2.2, dodgeLag: 0.32, jitter: 0.12 },
    audio: {
      ambient: 'breeze',
      rainGain: 0,
      windGain: 0.16,
      droneGain: 0,
      hailPerSecond: 0,
      thunderPerMinute: 0,
      thunderAudible: false,
      siren: false,
      click: 'woodblock',
    },
    effects: {
      sun: 0.32,
      cloud: 0.5,
      cloudLayers: 5,
      dust: 0.3,
      leaves: 0.5,
      rain: 0,
      rainLength: 1,
      ripples: 0,
      waterDrops: 0,
      hail: 0,
      debris: 0,
      lightningPerSecond: 0,
      vortex: 0,
      streaks: 0.25,
      shake: 0,
      strobe: 0,
      contrast: 0.08,
      heat: 0.2,
    },
    prayers: ['云聚！', '再厚一点', '挡住太阳', '风起云涌', '再来！'],
  },
  {
    index: 2,
    key: 'overcast',
    name: '阴天',
    tagline: '乌云压顶，天光只剩下一条缝',
    hint: '再用力点！',
    advanceGain: 0.19,
    decayPerSec: 0.09,
    graceMs: 250,
    palette: {
      skyTop: '#48586a',
      skyMid: '#6b7a88',
      skyBottom: '#93a0aa',
      sun: '#cfd6d8',
      cloud: '#aab5bd',
      cloudShade: '#7c878f',
      ground: '#4f6a58',
      accent: '#a9b6c0',
      text: '#eaf1f6',
      vignette: '#1d2a35',
      vignetteStrength: 0.3,
    },
    wind: { amp: 20, freq: 0.55, dodge: 0.35, dodgeRadius: 2.2, dodgeLag: 0.3, jitter: 0.2 },
    audio: {
      ambient: 'drone',
      rainGain: 0,
      windGain: 0.28,
      droneGain: 0.24,
      hailPerSecond: 0,
      thunderPerMinute: 0,
      thunderAudible: false,
      siren: false,
      click: 'thud',
    },
    effects: {
      sun: 0.06,
      cloud: 0.8,
      cloudLayers: 7,
      dust: 0.4,
      leaves: 0.35,
      rain: 0,
      rainLength: 1.1,
      ripples: 0,
      waterDrops: 0.05,
      hail: 0,
      debris: 0,
      // 远景无声闪电：有闪，但没有雷声
      lightningPerSecond: 0.07,
      vortex: 0,
      streaks: 0.4,
      shake: 0,
      strobe: 0,
      contrast: 0.3,
      heat: 0,
    },
    prayers: ['压下来', '再厚些', '要下雨了', '雷在酝酿', '天更暗了'],
  },
  {
    index: 3,
    key: 'rain',
    name: '雨',
    tagline: '细雨落下，屋檐开始敲鼓',
    hint: '雨来了！继续！',
    advanceGain: 0.17,
    decayPerSec: 0.11,
    graceMs: 260,
    palette: {
      skyTop: '#2f4055',
      skyMid: '#43596c',
      skyBottom: '#5d7285',
      sun: '#9fb4c4',
      cloud: '#8b9dad',
      cloudShade: '#5b6c7b',
      ground: '#3d564f',
      accent: '#7fd4ff',
      text: '#eaf6ff',
      vignette: '#101c26',
      vignetteStrength: 0.45,
    },
    wind: { amp: 30, freq: 0.62, dodge: 0.6, dodgeRadius: 2.2, dodgeLag: 0.26, jitter: 0.3 },
    audio: {
      ambient: 'rain',
      rainGain: 0.42,
      windGain: 0.3,
      droneGain: 0.12,
      hailPerSecond: 0,
      thunderPerMinute: 6,
      thunderAudible: true,
      siren: false,
      click: 'drop',
    },
    effects: {
      sun: 0,
      cloud: 0.88,
      cloudLayers: 7,
      dust: 0.15,
      leaves: 0.2,
      rain: 0.5,
      rainLength: 1.15,
      ripples: 0.6,
      waterDrops: 0.4,
      hail: 0,
      debris: 0,
      lightningPerSecond: 0.1,
      vortex: 0,
      streaks: 0.5,
      shake: 0.06,
      strobe: 0,
      contrast: 0.42,
      heat: 0,
    },
    prayers: ['雨落！', '大一点', '下满整条街', '屋檐在响', '别停手'],
  },
  {
    index: 4,
    key: 'storm',
    name: '暴雨',
    tagline: '暴雨倾盆，雷声就在头顶炸开',
    hint: '别停！暴雨了！',
    advanceGain: 0.15,
    decayPerSec: 0.13,
    graceMs: 270,
    palette: {
      skyTop: '#151d28',
      skyMid: '#243342',
      skyBottom: '#35485a',
      sun: '#7f95a8',
      cloud: '#5a6b7b',
      cloudShade: '#33414e',
      ground: '#283b3a',
      accent: '#6fe3ff',
      text: '#eff8ff',
      vignette: '#05090d',
      vignetteStrength: 0.6,
    },
    wind: { amp: 42, freq: 0.7, dodge: 0.85, dodgeRadius: 2.3, dodgeLag: 0.22, jitter: 0.42 },
    audio: {
      ambient: 'downpour',
      rainGain: 0.72,
      windGain: 0.46,
      droneGain: 0.2,
      hailPerSecond: 0,
      thunderPerMinute: 40,
      thunderAudible: true,
      siren: false,
      click: 'crack',
    },
    effects: {
      sun: 0,
      cloud: 0.95,
      cloudLayers: 8,
      dust: 0.1,
      leaves: 0.3,
      rain: 0.85,
      rainLength: 1.8,
      ripples: 0.95,
      waterDrops: 0.65,
      hail: 0.12,
      debris: 0.25,
      lightningPerSecond: 0.55,
      vortex: 0,
      streaks: 0.75,
      shake: 0.55,
      strobe: 0,
      contrast: 0.6,
      heat: 0,
    },
    prayers: ['暴雨！', '再猛些', '雷声助我', '倾盆而下', '天地混一色'],
  },
  {
    index: 5,
    key: 'severe',
    name: '强对流',
    tagline: '雷暴大风冰雹齐至，天在旋涡里发怒',
    hint: '抓住我！',
    advanceGain: 0.13,
    decayPerSec: 0.15,
    graceMs: 280,
    palette: {
      skyTop: '#0d0a16',
      skyMid: '#1d1430',
      skyBottom: '#332445',
      sun: '#8f7fb0',
      cloud: '#463456',
      cloudShade: '#241a33',
      ground: '#1d1a26',
      accent: '#c58bff',
      text: '#f7f0ff',
      vignette: '#04030a',
      vignetteStrength: 0.72,
    },
    wind: { amp: 60, freq: 0.8, dodge: 1, dodgeRadius: 2.4, dodgeLag: 0.18, jitter: 0.55 },
    audio: {
      ambient: 'tempest',
      rainGain: 0.62,
      windGain: 0.66,
      droneGain: 0.26,
      hailPerSecond: 3.2,
      thunderPerMinute: 90,
      thunderAudible: true,
      siren: true,
      click: 'zap',
    },
    effects: {
      sun: 0,
      cloud: 1,
      cloudLayers: 9,
      dust: 0.1,
      leaves: 0.4,
      rain: 0.9,
      rainLength: 2.1,
      ripples: 1,
      waterDrops: 0.5,
      hail: 0.8,
      debris: 0.9,
      lightningPerSecond: 1.5,
      vortex: 1,
      streaks: 0.9,
      shake: 1,
      strobe: 0.6,
      contrast: 0.72,
      heat: 0,
    },
    prayers: ['天地同应', '雷霆万钧', '冰雹也来', '风暴中心', '诚心感天'],
  },
]

export const STAGE_COUNT = STAGES.length
export const LAST_STAGE_INDEX = STAGE_COUNT - 1

export function stageAt(index: number): StageDef {
  const i = index < 0 ? 0 : index > LAST_STAGE_INDEX ? LAST_STAGE_INDEX : Math.floor(index)
  return STAGES[i] as StageDef
}

export function comboMultiplier(combo: number): number {
  let tier = 0
  for (const threshold of COMBO_TIERS) {
    if (combo >= threshold) tier += 1
  }
  return COMBO_MULTIPLIERS[tier] ?? 1
}

/** 距离下一档连击还差几次（用于 HUD 提示）。 */
export function comboNextTier(combo: number): number | null {
  for (const threshold of COMBO_TIERS) {
    if (combo < threshold) return threshold
  }
  return null
}
